repo: fix accessing property on possible null value in getIssues
If issues[0] returns null or undefined, accessing the pull_request property
will cause it to fail.

TypeError: Cannot read property 'pull_request' of undefined
    at null.<anonymous> (/Users/parker/jekyll/haunt/node_modules/haunt/lib/repo.js:156:23)